import { createHash } from 'node:crypto'
import { lstat, mkdir, open, realpath, rmdir, unlink } from 'node:fs/promises'
import path from 'node:path'
import { validatePluginSourceV1 } from '../index.mjs'
import { PluginValidationError } from '../runtime/manifest-v1.mjs'

const packageManager = 'pnpm@9.15.9'
const typescriptVersion = '5.9.2'

function failUsage() { throw new PluginValidationError('CLI_USAGE', 'manifest.json') }
function failSource() { throw new PluginValidationError('SOURCE_IO', 'manifest.json') }
function failExists() { throw new PluginValidationError('OUTPUT_EXISTS', 'manifest.json') }

function sameIdentity(left, right) {
  return left.dev === right.dev && left.ino === right.ino && left.size === right.size && left.mtimeMs === right.mtimeMs
}

function sameObject(left, right) { return left.dev === right.dev && left.ino === right.ino }

function isInside(root, candidate) {
  const relative = path.relative(root, candidate)
  return relative === '' || (!relative.startsWith(`..${path.sep}`) && relative !== '..' && !path.isAbsolute(relative))
}

function safeSegments(directory) {
  if (typeof directory !== 'string' || !directory || directory.length > 1024 || path.isAbsolute(directory) || path.win32.isAbsolute(directory) || /^[A-Za-z]:/.test(directory)) failUsage()
  const segments = directory.replaceAll('\\', '/').split('/')
  const safe = []
  for (const segment of segments) {
    if (!segment || segment === '..') failUsage()
    if (segment === '.') continue
    if (segment.length > 200 || /[<>:"|?*\x00-\x1f\x7f]/.test(segment) || /[. ]$/.test(segment) || /^(?:con|prn|aux|nul|com[1-9¹²³]|lpt[1-9¹²³])(?:\.|$)/i.test(segment)) failUsage()
    safe.push(segment)
  }
  if (!safe.length) failUsage()
  return safe
}

function truncateUtf16(value, maxLength) {
  let result = ''
  for (const character of value) {
    if (result.length + character.length > maxLength) break
    result += character
  }
  return result
}

function humanizedName(directoryName) {
  const candidate = directoryName.replace(/[._-]+/g, ' ').replace(/\s+/g, ' ').trim() || 'Basic Plugin'
  return truncateUtf16(candidate, 80)
}

function slugFor(value) {
  const slug = value.normalize('NFKD').replace(/\p{M}/gu, '').toLowerCase().replace(/[^a-z0-9]+/g, '.').replace(/^\.+|\.+$/g, '').slice(0, 96).replace(/\.+$/g, '')
  return slug || `plugin.${createHash('sha256').update(value, 'utf8').digest('hex').slice(0, 12)}`
}

function buildManifest(directoryName, options) {
  const name = options.name ?? humanizedName(directoryName)
  const slug = slugFor(directoryName)
  return {
    manifestVersion: 1,
    id: options.id ?? `org.example.${slug}`,
    name,
    description: options.description ?? 'A basic WebTools declarative plugin.',
    author: { name: options.author ?? 'Plugin author' },
    version: '1.0.0',
    api: { apiMajor: 1, minHostVersion: options.minHostVersion ?? options.hostVersion },
    type: 'declarative-manager',
    entry: { pageId: 'home', label: name },
    requestedCapabilities: ['manager.page'],
    settings: [],
    pages: [{ id: 'home', title: name, blocks: [{ type: 'heading', text: name }, { type: 'paragraph', text: options.description ?? 'A basic WebTools declarative plugin.' }] }],
    actions: [],
    assets: [],
  }
}

function generatedFiles(manifest, hostVersion, slug) {
  const packageSlug = slug.replaceAll('.', '-')
  const packageName = `webtools-plugin-${packageSlug}`
  const artifact = `./dist/${packageSlug}.wtplugin`
  const packageJson = {
    name: packageName,
    version: '1.0.0',
    private: true,
    type: 'module',
    packageManager,
    scripts: {
      typecheck: 'tsc --noEmit --strict --skipLibCheck --moduleResolution bundler --module ESNext --target ES2022 manifest.typecheck.ts',
      validate: `webtools-plugin validate . --host-version ${hostVersion}`,
      'plugin:pack': `webtools-plugin pack . --out ${artifact} --host-version ${hostVersion}`,
      inspect: `webtools-plugin inspect ${artifact} --host-version ${hostVersion}`,
    },
    devDependencies: { typescript: typescriptVersion },
  }
  const typecheckSource = `import type { PluginManifestV1 } from '@webtools/plugin-sdk'\n\nexport const manifest = ${JSON.stringify(manifest, null, 2)} satisfies PluginManifestV1\n`
  const readme = [
    `# ${manifest.name}`,
    '',
    'This is a basic WebTools declarative plugin starter generated by **webtools-plugin create**. It contains only a Manifest v1 page and the **manager.page** capability. It cannot run plugin JavaScript, Node.js, HTML, Vue, or arbitrary IPC.',
    '',
    '## Set up the local SDK',
    '',
    'Use the local SDK tarball **@webtools/plugin-sdk@1.1.0** supplied with the WebTools developer tools. The SDK is distributed locally and is not published to npm. Add that same local SDK tarball as a development dependency (adjust the relative path if you store it elsewhere):',
    '',
    '```powershell',
    'pnpm add --save-dev file:../../artifacts/webtools-plugin-sdk-1.1.0.tgz',
    'pnpm install --frozen-lockfile',
    '```',
    '',
    '## Author workflow',
    '',
    '```powershell',
    'pnpm run typecheck',
    'pnpm run validate',
    'pnpm run plugin:pack',
    'pnpm run inspect',
    '```',
    '',
    "The **plugin:pack** name is deliberate: **pnpm pack** is pnpm's built-in command for creating the SDK Node package tarball. The generated **.wtplugin** is written under **dist/**. WebTools Plugin Center performs a separate authoritative validation and consent flow when installing it.",
    '',
  ].join('\n')
  const gitignore = 'node_modules/\ndist/*.wtplugin\n'
  return [
    ['manifest.json', `${JSON.stringify(manifest, null, 2)}\n`],
    ['manifest.typecheck.ts', typecheckSource],
    ['package.json', `${JSON.stringify(packageJson, null, 2)}\n`],
    ['README.md', readme],
    ['.gitignore', gitignore],
  ]
}

async function verifyDirectory(root, directory, identity) {
  const info = await lstat(directory).catch(() => failSource())
  if (!info.isDirectory() || info.isSymbolicLink() || !sameObject(identity, info)) failSource()
  const resolved = await realpath(directory).catch(() => failSource())
  if (!isInside(root, resolved)) failSource()
}

async function cleanupOwned(created) {
  for (const item of created.reverse()) {
    try {
      const current = await lstat(item.path)
      if (item.directory ? !sameObject(item.identity, current) : !sameIdentity(item.identity, current)) continue
      if (item.directory) await rmdir(item.path)
      else await unlink(item.path)
    } catch { /* Preserve replacements and any content not owned by this invocation. */ }
  }
}

async function createDirectory(target, created) {
  try { await mkdir(target, { mode: 0o700 }) }
  catch (error) {
    if (error?.code === 'EEXIST') failExists()
    throw error
  }
  const identity = await lstat(target)
  created.push({ path: target, identity, directory: true })
  return identity
}

async function writeOwnedFile(root, target, targetIdentity, relativeFile, contents, created) {
  await verifyDirectory(root, target, targetIdentity)
  const destination = path.join(target, relativeFile)
  let handle
  try { handle = await open(destination, 'wx', 0o600) }
  catch { failSource() }
  let owned
  try {
    owned = { path: destination, identity: await handle.stat(), directory: false }
    created.push(owned)
    // Revalidate after opening and before writing. This catches a parent or
    // target directory replaced by a junction in the check/open window; the
    // opened file is still empty, so cleanup can remove only this file identity.
    await verifyDirectory(root, target, targetIdentity)
    const [resolvedTarget, resolvedDestination, destinationInfo] = await Promise.all([
      realpath(target).catch(() => failSource()),
      realpath(destination).catch(() => failSource()),
      lstat(destination).catch(() => failSource()),
    ])
    if (!isInside(root, resolvedDestination)
      || path.relative(resolvedTarget, resolvedDestination) !== relativeFile
      || !sameObject(owned.identity, destinationInfo)) failSource()
    await verifyDirectory(root, target, targetIdentity)
    await handle.writeFile(contents, 'utf8')
    await handle.sync()
  } finally {
    if (owned) owned.identity = await handle.stat().catch(() => owned.identity)
    await handle.close()
  }
}

export async function createPluginStarter(directory, options) {
  const segments = safeSegments(directory)
  if (!options || typeof options.hostVersion !== 'string' || !/^[0-9A-Za-z.+-]{1,128}$/.test(options.hostVersion)) failUsage()

  let root
  try { root = await realpath(process.cwd()) } catch { failSource() }
  let parent = root
  for (const segment of segments.slice(0, -1)) {
    parent = path.join(parent, segment)
    let info
    try { info = await lstat(parent) } catch { failUsage() }
    if (!info.isDirectory() || info.isSymbolicLink()) failUsage()
    const resolved = await realpath(parent).catch(() => failSource())
    if (!isInside(root, resolved)) failUsage()
    parent = resolved
  }

  const target = path.join(parent, segments.at(-1))
  try { await lstat(target); failExists() }
  catch (error) { if (error?.code !== 'ENOENT') throw error }

  const targetRelative = segments.join('/')
  const manifest = buildManifest(segments.at(-1), options)
  const slug = slugFor(segments.at(-1))
  const files = generatedFiles(manifest, options.hostVersion, slug)
  const created = []

  try {
    const targetIdentity = await createDirectory(target, created)
    await verifyDirectory(root, target, targetIdentity)
    const dist = path.join(target, 'dist')
    await mkdir(dist, { mode: 0o700 })
    created.push({ path: dist, identity: await lstat(dist), directory: true })

    for (const [relativeFile, contents] of files) {
      await writeOwnedFile(root, target, targetIdentity, relativeFile, contents, created)
    }

    const validated = await validatePluginSourceV1(target, options.hostVersion)
    return { directory: targetRelative, manifest: validated.manifest }
  } catch (error) {
    await cleanupOwned(created)
    if (error instanceof PluginValidationError) throw error
    failSource()
  }
}
